"""empty message

Revision ID: 1bfc0f6e10fb
Revises: 4816e84f0eeb
Create Date: 2013-10-07 17:41:30.538855

"""

# revision identifiers, used by Alembic.
revision = '1bfc0f6e10fb'
down_revision = '4816e84f0eeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'profile_pic')
    ### end Alembic commands ###
