"""Add integration for flask-security

Revision ID: 298608e6419f
Revises: 3977e94bf67c
Create Date: 2013-10-07 18:19:41.040992

"""

# revision identifiers, used by Alembic.
revision = '298608e6419f'
down_revision = '3977e94bf67c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_ip', sa.String(length=50), nullable=True))
    op.add_column(u'user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('last_login_ip', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('login_count', sa.String(length=50), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'login_count')
    op.drop_column(u'user', 'last_login_ip')
    op.drop_column(u'user', 'last_login_at')
    op.drop_column(u'user', 'current_login_ip')
    op.drop_column(u'user', 'current_login_at')
    op.drop_column(u'user', 'confirmed_at')
    op.drop_column(u'user', 'active')
    op.drop_table('roles_users')
    op.drop_table('role')
    ### end Alembic commands ###
