"""Fix login count type from string to integer

Revision ID: 352aaa6aba0e
Revises: 51d5eb7ab360
Create Date: 2013-10-11 01:14:04.672799

"""

# revision identifiers, used by Alembic.
revision = '352aaa6aba0e'
down_revision = '51d5eb7ab360'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
