"""make the profile_pic field optional

Revision ID: 3977e94bf67c
Revises: 1bfc0f6e10fb
Create Date: 2013-10-07 17:48:22.551916

"""

# revision identifiers, used by Alembic.
revision = '3977e94bf67c'
down_revision = '1bfc0f6e10fb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'profile_pic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'profile_pic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    ### end Alembic commands ###
