"""empty message

Revision ID: 3eca9f22e42
Revises: None
Create Date: 2013-09-29 21:55:55.898887

"""

# revision identifiers, used by Alembic.
revision = '3eca9f22e42'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge', 'thread_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge', 'thread_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
