"""empty message

Revision ID: 4816e84f0eeb
Revises: None
Create Date: 2013-10-07 17:38:32.495897

"""

# revision identifiers, used by Alembic.
revision = '4816e84f0eeb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('company_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'company_id')
    op.drop_table('company')
    ### end Alembic commands ###
