"""Make only email and password required for User model

Revision ID: 51d5eb7ab360
Revises: 298608e6419f
Create Date: 2013-10-07 18:42:00.689539

"""

# revision identifiers, used by Alembic.
revision = '51d5eb7ab360'
down_revision = '298608e6419f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'badge_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'challenge_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'daily_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('user', 'fb',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'fitbit_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'hide_progress',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'leader',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'oauth_secret',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('user', 'oauth_token',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'phantom',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'profile_pic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'profile_pic',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'phantom',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'oauth_token',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('user', 'oauth_secret',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('user', 'leader',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'hide_progress',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'fitbit_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'fb',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('user', 'daily_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'challenge_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'badge_email_unsub',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    ### end Alembic commands ###
